name: Run Python Script

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # Позволит запускать вручную для тестов

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Установка Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Установка зависимостей
        run: python -m pip install --upgrade pip

      - name: Показать структуру файлов
        run: ls -R

      - name: Запуск скрипта
        run: python wel/practic.py